export {default as ArtLogo} from './artart.svg';
export {default as ArtLogoShort} from './artartShort.svg';
export {default as ArtLogoFooter} from './artart_footer.svg';
export {default as SearchIcon} from './Icons/Search.svg';
export {default as MenuIcon} from './Icons/Menu.svg';
export {default as LikeIcon} from './Icons/LikeTag.svg';
export {default as LikeIconUnfilled} from './Icons/LikeTagUnfilled.svg';
export {default as ShareIcon} from './Icons/Share.svg';
export {default as VkIcon} from './Icons/Vk.svg';
export {default as InstagramIcon} from './Icons/Instagram.svg';
export {default as WebIcon} from './Icons/Web.svg';
export {default as EmailIcon} from './Icons/Email.svg';
export {default as PasswordIcon} from './Icons/Password.svg';
export {default as UserNameIcon} from './Icons/UserName.svg';
export {default as CalloutSuccessIcon} from './Icons/CalloutSuccess.svg';
export {default as CloseIcon} from './Icons/Close.svg';
export {default as DarkThemeIcon} from './Icons/Moon.svg';
export {default as LightThemeIcon} from './Icons/Sun.svg';

